title: Geronimo's Blog for Brookes
description: A website with a blog :D
header_text: Energy Typography
footer_text: Copyright 2020 Geronimo Villaveces
header_feature_image: ../uploads/background.png
bannerheight: 20vmax
logo: ../uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
